# -*- coding:utf-8 -*-

import pygame.locals


class Config:
    # game state
    GAME_STATE_MENU = 0
    GAME_STATE_SETTING = 1
    GAME_STATE_GAMING = 2
    GAME_STATE = GAME_STATE_MENU

    # display config
    DISPLAY_MODE_FULLSCREEN = pygame.FULLSCREEN | pygame.HWSURFACE
    DISPLAY_MODE_WINDOW = 0
    DISPLAY_MODE = DISPLAY_MODE_WINDOW

    DISPLAY_RESOLUTION_FULLSCREEN = (1920, 1080)
    DISPLAY_RESOLUTION_WINDOW = (1280, 720)
    DISPLAY_RESOLUTION = DISPLAY_RESOLUTION_WINDOW

    # music config
    MUSIC_PATH = r'../sound'
    MUSIC_FILE_STATE_INIT = -1
    MUSIC_FILE_STATE_NORMAL = 0
    MUSIC_FILE_STATE_NOT_FOUND = 1
    MUSIC_FILE_STATE = MUSIC_FILE_STATE_INIT

    MUSIC_INDEX = 0
    MUSIC_MAX_INDEX = 0

    MUSIC_STATE_INIT = 0
    MUSIC_STATE_PLAY = 1
    MUSIC_STATE_PAUSE = 2
    MUSIC_STATE_STOP = 3
    MUSIC_STATE = MUSIC_STATE_INIT

    MUSIC_VOLUME = 100
